defaults:
  - _self_
  - model: "genie-scope-128"
  - experiment: "none"

model:
  batch_size: 8
  device: "cuda"
  max_n_residues: ???

experiment:
  name: ???
  sweep_dir: "multirun/${experiment.name}/${now:%Y-%m-%d}/${now:%H-%M-%S_%f}"

hydra:
  help:
    app_name: "Motif-scaffolding experiments"
  run:
    dir: "outputs/${experiment.name}/${now:%Y-%m-%d}/${now:%H-%M-%S_%f}"
  sweep:
    dir: "${experiment.sweep_dir}"
    subdir: ${hydra.job.num}
